POST {{baseUrl}}/souls HTTP/1.1
content-type: application/json

{
    "displayName": "Alastair"
}

###

GET {{baseUrl}}/souls/{{id}} HTTP/1.1
Content-Type: application/json

### Variables
@id = 20258bb0-d291-4c27-bf1f-cc0a8d4ccf4b