FROM golang:alpine AS build
WORKDIR /backend
COPY . .
RUN go build -o /backend/bin/server backend/server.go

FROM scratch
COPY --from=build /backend/bin/server /backend/bin/server

EXPOSE 8080

ENTRYPOINT [ "/backend/bin/server" ]